### ISSUE TITLE
add free$hop

### ISSUE THREAD

**Issue by Poliwrath** [pillows2/3dsplaykit#1]
add freeshop

**Comment by GabrielRRussell** [comment]
Nope. Bad idea, and associates our scene with illegal activity.

If you want to pirate, do it on your own time. Not our time.

Regardless, this is for tools, games, software, anything neat that anyone should have with their first homebrew installation.

**Comment by Poliwrath** [comment]
freeshop is something somebody should have with their first time setup

**Comment by pillows2** [comment]
Then I wouldnt be able to post it to the shacks sub

**Comment by GabrielRRussell** [comment]
+1 for the term shacks

**Comment by Poliwrath** [comment]
but u dont have to post it there

**Comment by pillows2** [comment]
im not gonna do it, case closed

also adding a thumbs up emoji to your comments is *definitely* gonna help :P

**Comment by Poliwrath** [comment]
and putting emoticons on my comments also to help

**Comment by pillows2** [comment]
well its not going to, so stop commenting
