### ISSUE TITLE
Embed MD files for documentation.

### ISSUE THREAD

**Issue by GabrielRRussell** [pillows2/3dsplaykit#2]
You can embed github gists (in .md format) easily by using some simple HTML. It would make sense to be able to carry over formatting for documentation.

To embed a gist, you would just use code like this: <script src="https://gist.github.com/Kaisogen/6a56a4a6c8a9d95dd4c0a7d9e092ccf0.js"></script> (this is one of my gists)

If you want, I can help write some gists on documentation of the games / tools.

**Comment by pillows2** [comment]
Sure, will do when I'm home
