### ISSUE TITLE
Add Brewman

### ISSUE THREAD

**Issue by dvdcd** [pillows2/3dsplaykit#3]
can you add brewman or some of the apps on it?

**Comment by Kaisogen** [comment]
Can you link me to some of the apps you want? We're still taking suggestions. I'll look into Brewman.

**Comment by dvdcd** [comment]
Makes sense, i might work on it a bit soon as its sorta dead because you cannot add new apps to it

**Comment by Kaisogen** [comment]
Alright, sounds good on me. Are there any other suggestions you have?

**Comment by dvdcd** [comment]
not yet, but i might have some later

**Comment by GabrielRRussell** [comment]
If this is all you have to say, I'll close this issue for now.

**Comment by pillows2** [comment]
Hey what's Brewman?

**Comment by Kaisogen** [comment]
Brewman is similar to Homeb3w, a tool for downloading homebrew. The difference being that Brewman downloads applications in 3DSX format.

**Comment by dvdcd** [comment]
Hey @pillows2, would you mind deleting this issue from the repository entirely? 
I was pretty young at time of writing and didn't understand the gravity of what I was asking, and don't really want this issue sticking around on my Github account till the end of time.

(edit: my bad, looks like Pillows2 is the repository owner, and only repository owners can fully delete issues)
